import React from "react";

export function Icon() {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="36"
      height="36"
      version="1.1"
      viewBox="0 0 101.6 101.6"
    >
      <defs>
        <filter
          width="1"
          height="1"
          x="0"
          y="0"
          colorInterpolationFilters="sRGB"
        >
          <feColorMatrix
            result="result3"
            type="saturate"
            values="0"
          ></feColorMatrix>
          <feColorMatrix
            in="SourceGraphic"
            result="colormatrix"
            values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 -0.5 -0.5 0 0"
          ></feColorMatrix>
          <feFlood
            floodColor="#440086"
            floodOpacity="1"
            result="result1"
          ></feFlood>
          <feComposite
            in2="colormatrix"
            operator="in"
            result="result2"
          ></feComposite>
          <feComposite
            in2="colormatrix"
            k1="0"
            k2="1"
            k3="-0.5"
            k4="0"
            operator="arithmetic"
            result="result12"
          ></feComposite>
          <feBlend
            in="result12"
            in2="result3"
            mode="normal"
            result="result6"
          ></feBlend>
          <feColorMatrix
            in="SourceGraphic"
            result="colormatrix"
            values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 -0.5 1 -0.5 0 0"
          ></feColorMatrix>
          <feFlood
            floodColor="#FE3F00"
            floodOpacity="1"
            result="result4"
          ></feFlood>
          <feComposite
            in2="colormatrix"
            operator="in"
            result="result5"
          ></feComposite>
          <feComposite
            in2="colormatrix"
            k1="0"
            k2="1"
            k3="-0.5"
            k4="0"
            operator="arithmetic"
            result="result13"
          ></feComposite>
          <feBlend
            in="result13"
            in2="result6"
            mode="normal"
            result="result9"
          ></feBlend>
          <feColorMatrix
            in="SourceGraphic"
            result="colormatrix"
            values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 -0.5 -0.5 1 0 0"
          ></feColorMatrix>
          <feFlood
            floodColor="#FC0"
            floodOpacity="1"
            result="result7"
          ></feFlood>
          <feComposite
            in2="colormatrix"
            operator="in"
            result="result8"
          ></feComposite>
          <feComposite
            in2="colormatrix"
            k1="0"
            k2="1"
            k3="-0.5"
            k4="0"
            operator="arithmetic"
            result="result14"
          ></feComposite>
          <feBlend
            in="result14"
            in2="result9"
            mode="normal"
            result="result10"
          ></feBlend>
          <feComposite
            in="result10"
            in2="SourceGraphic"
            operator="in"
            result="result11"
          ></feComposite>
        </filter>
        <filter
          width="1"
          height="1"
          x="0"
          y="0"
          colorInterpolationFilters="sRGB"
        >
          <feColorMatrix
            result="result3"
            type="saturate"
            values="0"
          ></feColorMatrix>
          <feColorMatrix
            in="SourceGraphic"
            result="colormatrix"
            values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 -0.5 -0.5 0 0"
          ></feColorMatrix>
          <feFlood
            floodColor="#440086"
            floodOpacity="1"
            result="result1"
          ></feFlood>
          <feComposite
            in2="colormatrix"
            operator="in"
            result="result2"
          ></feComposite>
          <feComposite
            in2="colormatrix"
            k1="0"
            k2="1"
            k3="-0.5"
            k4="0"
            operator="arithmetic"
            result="result12"
          ></feComposite>
          <feBlend
            in="result12"
            in2="result3"
            mode="normal"
            result="result6"
          ></feBlend>
          <feColorMatrix
            in="SourceGraphic"
            result="colormatrix"
            values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 -0.5 1 -0.5 0 0"
          ></feColorMatrix>
          <feFlood
            floodColor="#FE3F00"
            floodOpacity="1"
            result="result4"
          ></feFlood>
          <feComposite
            in2="colormatrix"
            operator="in"
            result="result5"
          ></feComposite>
          <feComposite
            in2="colormatrix"
            k1="0"
            k2="1"
            k3="-0.5"
            k4="0"
            operator="arithmetic"
            result="result13"
          ></feComposite>
          <feBlend
            in="result13"
            in2="result6"
            mode="normal"
            result="result9"
          ></feBlend>
          <feColorMatrix
            in="SourceGraphic"
            result="colormatrix"
            values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 -0.5 -0.5 1 0 0"
          ></feColorMatrix>
          <feFlood
            floodColor="#FC0"
            floodOpacity="1"
            result="result7"
          ></feFlood>
          <feComposite
            in2="colormatrix"
            operator="in"
            result="result8"
          ></feComposite>
          <feComposite
            in2="colormatrix"
            k1="0"
            k2="1"
            k3="-0.5"
            k4="0"
            operator="arithmetic"
            result="result14"
          ></feComposite>
          <feBlend
            in="result14"
            in2="result9"
            mode="normal"
            result="result10"
          ></feBlend>
          <feComposite
            in="result10"
            in2="SourceGraphic"
            operator="in"
            result="result11"
          ></feComposite>
        </filter>
        <filter
          width="1"
          height="1"
          x="0"
          y="0"
          colorInterpolationFilters="sRGB"
        >
          <feColorMatrix
            result="result3"
            type="saturate"
            values="0"
          ></feColorMatrix>
          <feColorMatrix
            in="SourceGraphic"
            result="colormatrix"
            values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 -0.5 -0.5 0 0"
          ></feColorMatrix>
          <feFlood
            floodColor="#440086"
            floodOpacity="1"
            result="result1"
          ></feFlood>
          <feComposite
            in2="colormatrix"
            operator="in"
            result="result2"
          ></feComposite>
          <feComposite
            in2="colormatrix"
            k1="0"
            k2="1"
            k3="-0.5"
            k4="0"
            operator="arithmetic"
            result="result12"
          ></feComposite>
          <feBlend
            in="result12"
            in2="result3"
            mode="normal"
            result="result6"
          ></feBlend>
          <feColorMatrix
            in="SourceGraphic"
            result="colormatrix"
            values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 -0.5 1 -0.5 0 0"
          ></feColorMatrix>
          <feFlood
            floodColor="#FE3F00"
            floodOpacity="1"
            result="result4"
          ></feFlood>
          <feComposite
            in2="colormatrix"
            operator="in"
            result="result5"
          ></feComposite>
          <feComposite
            in2="colormatrix"
            k1="0"
            k2="1"
            k3="-0.5"
            k4="0"
            operator="arithmetic"
            result="result13"
          ></feComposite>
          <feBlend
            in="result13"
            in2="result6"
            mode="normal"
            result="result9"
          ></feBlend>
          <feColorMatrix
            in="SourceGraphic"
            result="colormatrix"
            values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 -0.5 -0.5 1 0 0"
          ></feColorMatrix>
          <feFlood
            floodColor="#FC0"
            floodOpacity="1"
            result="result7"
          ></feFlood>
          <feComposite
            in2="colormatrix"
            operator="in"
            result="result8"
          ></feComposite>
          <feComposite
            in2="colormatrix"
            k1="0"
            k2="1"
            k3="-0.5"
            k4="0"
            operator="arithmetic"
            result="result14"
          ></feComposite>
          <feBlend
            in="result14"
            in2="result9"
            mode="normal"
            result="result10"
          ></feBlend>
          <feComposite
            in="result10"
            in2="SourceGraphic"
            operator="in"
            result="result11"
          ></feComposite>
        </filter>
        <filter
          width="1"
          height="1"
          x="0"
          y="0"
          colorInterpolationFilters="sRGB"
        >
          <feColorMatrix
            result="result3"
            type="saturate"
            values="0"
          ></feColorMatrix>
          <feColorMatrix
            in="SourceGraphic"
            result="colormatrix"
            values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 -0.5 -0.5 0 0"
          ></feColorMatrix>
          <feFlood
            floodColor="#440086"
            floodOpacity="1"
            result="result1"
          ></feFlood>
          <feComposite
            in2="colormatrix"
            operator="in"
            result="result2"
          ></feComposite>
          <feComposite
            in2="colormatrix"
            k1="0"
            k2="1"
            k3="-0.5"
            k4="0"
            operator="arithmetic"
            result="result12"
          ></feComposite>
          <feBlend
            in="result12"
            in2="result3"
            mode="normal"
            result="result6"
          ></feBlend>
          <feColorMatrix
            in="SourceGraphic"
            result="colormatrix"
            values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 -0.5 1 -0.5 0 0"
          ></feColorMatrix>
          <feFlood
            floodColor="#FE3F00"
            floodOpacity="1"
            result="result4"
          ></feFlood>
          <feComposite
            in2="colormatrix"
            operator="in"
            result="result5"
          ></feComposite>
          <feComposite
            in2="colormatrix"
            k1="0"
            k2="1"
            k3="-0.5"
            k4="0"
            operator="arithmetic"
            result="result13"
          ></feComposite>
          <feBlend
            in="result13"
            in2="result6"
            mode="normal"
            result="result9"
          ></feBlend>
          <feColorMatrix
            in="SourceGraphic"
            result="colormatrix"
            values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 -0.5 -0.5 1 0 0"
          ></feColorMatrix>
          <feFlood
            floodColor="#FC0"
            floodOpacity="1"
            result="result7"
          ></feFlood>
          <feComposite
            in2="colormatrix"
            operator="in"
            result="result8"
          ></feComposite>
          <feComposite
            in2="colormatrix"
            k1="0"
            k2="1"
            k3="-0.5"
            k4="0"
            operator="arithmetic"
            result="result14"
          ></feComposite>
          <feBlend
            in="result14"
            in2="result9"
            mode="normal"
            result="result10"
          ></feBlend>
          <feComposite
            in="result10"
            in2="SourceGraphic"
            operator="in"
            result="result11"
          ></feComposite>
        </filter>
        <filter
          width="1"
          height="1"
          x="0"
          y="0"
          colorInterpolationFilters="sRGB"
        >
          <feColorMatrix
            result="result3"
            type="saturate"
            values="0"
          ></feColorMatrix>
          <feColorMatrix
            in="SourceGraphic"
            result="colormatrix"
            values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 -0.5 -0.5 0 0"
          ></feColorMatrix>
          <feFlood
            floodColor="#440086"
            floodOpacity="1"
            result="result1"
          ></feFlood>
          <feComposite
            in2="colormatrix"
            operator="in"
            result="result2"
          ></feComposite>
          <feComposite
            in2="colormatrix"
            k1="0"
            k2="1"
            k3="-0.5"
            k4="0"
            operator="arithmetic"
            result="result12"
          ></feComposite>
          <feBlend
            in="result12"
            in2="result3"
            mode="normal"
            result="result6"
          ></feBlend>
          <feColorMatrix
            in="SourceGraphic"
            result="colormatrix"
            values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 -0.5 1 -0.5 0 0"
          ></feColorMatrix>
          <feFlood
            floodColor="#FE3F00"
            floodOpacity="1"
            result="result4"
          ></feFlood>
          <feComposite
            in2="colormatrix"
            operator="in"
            result="result5"
          ></feComposite>
          <feComposite
            in2="colormatrix"
            k1="0"
            k2="1"
            k3="-0.5"
            k4="0"
            operator="arithmetic"
            result="result13"
          ></feComposite>
          <feBlend
            in="result13"
            in2="result6"
            mode="normal"
            result="result9"
          ></feBlend>
          <feColorMatrix
            in="SourceGraphic"
            result="colormatrix"
            values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 -0.5 -0.5 1 0 0"
          ></feColorMatrix>
          <feFlood
            floodColor="#FC0"
            floodOpacity="1"
            result="result7"
          ></feFlood>
          <feComposite
            in2="colormatrix"
            operator="in"
            result="result8"
          ></feComposite>
          <feComposite
            in2="colormatrix"
            k1="0"
            k2="1"
            k3="-0.5"
            k4="0"
            operator="arithmetic"
            result="result14"
          ></feComposite>
          <feBlend
            in="result14"
            in2="result9"
            mode="normal"
            result="result10"
          ></feBlend>
          <feComposite
            in="result10"
            in2="SourceGraphic"
            operator="in"
            result="result11"
          ></feComposite>
        </filter>
      </defs>
      <g
        strokeDashoffset="11.2"
        strokeLinejoin="round"
        paintOrder="markers stroke fill"
      >
        <path
          fill="#fff"
          stroke="none"
          strokeLinecap="round"
          strokeWidth="16"
          d="M65.767 65.767A21.167 21.167 0 0139.04 68.4a21.167 21.167 0 01-7.795-25.7A21.167 21.167 0 0154.929 30.04 21.167 21.167 0 0171.967 50.8H50.8z"
        ></path>
        <path
          fill="none"
          stroke="#fff"
          strokeDasharray="none"
          strokeLinecap="butt"
          strokeMiterlimit="4"
          strokeOpacity="1"
          strokeWidth="4.233"
          d="M80.433 50.8a29.633 29.633 0 01-.76 6.666"
        ></path>
        <path
          fill="none"
          stroke="#fff"
          strokeDasharray="none"
          strokeLinecap="butt"
          strokeMiterlimit="4"
          strokeOpacity="1"
          strokeWidth="4.233"
          d="M73.83 69.449a29.633 29.633 0 01-10.506 8.208"
        ></path>
        <path
          fill="none"
          stroke="#fff"
          strokeDasharray="none"
          strokeLinecap="butt"
          strokeMiterlimit="4"
          strokeOpacity="1"
          strokeWidth="4.233"
          d="M50.8 21.167A29.633 29.633 0 0177.434 37.81"
        ></path>
        <path
          fill="none"
          stroke="#fff"
          strokeDasharray="none"
          strokeLinecap="butt"
          strokeMiterlimit="4"
          strokeOpacity="1"
          strokeWidth="4.233"
          d="M23.729 62.853a29.633 29.633 0 01.906-25.965"
        ></path>
        <path
          fill="none"
          stroke="#fff"
          strokeDasharray="none"
          strokeLinecap="butt"
          strokeMiterlimit="4"
          strokeOpacity="1"
          strokeWidth="4.233"
          d="M50.283 80.429a29.633 29.633 0 01-18.53-6.929"
        ></path>
      </g>
    </svg>
  );
}

export default Icon;